# Generated by Django 3.1.1 on 2020-09-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Defintion',
            new_name='Definition',
        ),
    ]
